### PR TITLE
Update to 5.0.2

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jan-janssen** [comment]
@telegraphic Can you take a look at this pull request? It updates the conda package to the latest version of `hickle`.

**Comment by jan-janssen** [comment]
Fixes https://github.com/conda-forge/hickle-feedstock/issues/12

**Comment by jan-janssen** [comment]
@conda-forge/core As the recipe was not updated for over two years, it would be great if one of you could merge this, I am willing to take over the maintenance of this recipe.

**Comment by telegraphic** [comment]
Hi @jan-janssen, really appreciate you stepping in to update the recipe! :pray: 

FWIW I would be very happy to have your help maintaining the feedstock -- it has been languishing since I had kids, and I don't really understand how the conda-forge machinery fits together. I have just done some much-needed maintenance on the hickle repo too.

**Pull request merged**
